#!/usr/local/bin/perl -w
use strict;
my $faq_dir ='/usr/local/lib/perl5/5.6.1/pod/';
my @faq_files = ('perlfaq.pod', 'perlfaq1.pod', 'perlfaq2.pod', 'perlfaq3.pod',               'perlfaq4.pod', 'perlfaq6.pod', 'perlfaq8.pod', 'perlfaq5.pod'               , 'perlfaq7.pod', 'perlfaq9.pod'
		);

my $pattern = $ARGV[0] or die "no pattern given :$!";
foreach my $filename (@faq_files) 
       {

	 open(FILE,"$faq_dir/$filename") or die ("can't open '$filename': $!");
	 while (<FILE>) {
			if (s/^=head2// and m/$pattern/) 
			     {
			   print "$filename: \n$_";
		             }
	 
		        }
	 close FILE;
     }


	
