#! /bin/sh
# tbl-to-fasta.awk transforms a tbl file into a fasta file, 60 columns per record
# usage=gawk -f tbl-to-fasta TBL_FILE 


gawk '{
  sequence=$NF

  ls = length(sequence)
  is = 1
  fld  = 1

# if (fld == 1){printf ">"}
  
  while (fld < NF)
  {
     if (fld == 1){printf ">"}
     printf "%s " , $fld
    
     if (fld == NF-1)
      {
        printf "\n"
      }
      fld = fld+1
  }
  
  while (is <= ls)
  {
    printf "%s\n", substr(sequence,is,60)
    is=is+60
  }
}' "$@"
